const demoAnimeSeedData = [
  {
    animeId: 900001,
    title: "Attack on Titan",
    title_english: "Attack on Titan",
    title_japanese: "Shingeki no Kyojin",
    synopsis:
      "Humanity hides behind massive walls while Eren Yeager and his friends fight to survive against the Titans beyond them.",
    rating: 8.55,
    scored_by: 2500000,
    episodes: 25,
    status: "Finished Airing",
    type: "TV",
    season: "spring",
    year: 2013,
    seasonYear: "spring 2013",
    image: "https://cdn.myanimelist.net/images/anime/10/47347l.jpg",
    trailer: "https://www.youtube.com/embed/MGRm4IzK1SQ",
    trailerImage: "https://img.youtube.com/vi/MGRm4IzK1SQ/maxresdefault.jpg",
    source: "Manga",
    duration: "24 min per ep",
    popularity: 1,
    rank: 100,
    genres: [{ mal_id: 1, name: "Action" }, { mal_id: 8, name: "Drama" }],
    themes: [{ mal_id: 38, name: "Military" }, { mal_id: 58, name: "Survival" }],
    demographics: [{ mal_id: 27, name: "Shounen" }],
    studios: [{ mal_id: 858, name: "Wit Studio" }],
  },
  {
    animeId: 900002,
    title: "Fullmetal Alchemist: Brotherhood",
    title_english: "Fullmetal Alchemist: Brotherhood",
    title_japanese: "Hagane no Renkinjutsushi: Fullmetal Alchemist",
    synopsis:
      "Two brothers search for the Philosopher's Stone after a disastrous attempt to bring their mother back to life.",
    rating: 9.09,
    scored_by: 2200000,
    episodes: 64,
    status: "Finished Airing",
    type: "TV",
    season: "spring",
    year: 2009,
    seasonYear: "spring 2009",
    image: "https://cdn.myanimelist.net/images/anime/1208/94745l.jpg",
    trailer: "https://www.youtube.com/embed/2uq34TeWEdQ",
    trailerImage: "https://img.youtube.com/vi/2uq34TeWEdQ/maxresdefault.jpg",
    source: "Manga",
    duration: "24 min per ep",
    popularity: 3,
    rank: 2,
    genres: [{ mal_id: 1, name: "Action" }, { mal_id: 2, name: "Adventure" }],
    themes: [{ mal_id: 39, name: "Mythology" }],
    demographics: [{ mal_id: 27, name: "Shounen" }],
    studios: [{ mal_id: 4, name: "Bones" }],
  },
  {
    animeId: 900003,
    title: "Naruto",
    title_english: "Naruto",
    title_japanese: "Naruto",
    synopsis:
      "Naruto Uzumaki dreams of becoming Hokage while proving himself to a village that fears the power sealed inside him.",
    rating: 7.99,
    scored_by: 1900000,
    episodes: 220,
    status: "Finished Airing",
    type: "TV",
    season: "fall",
    year: 2002,
    seasonYear: "fall 2002",
    image: "https://cdn.myanimelist.net/images/anime/13/17405l.jpg",
    trailer: "https://www.youtube.com/embed/-G9BqkgZXRA",
    trailerImage: "https://img.youtube.com/vi/-G9BqkgZXRA/maxresdefault.jpg",
    source: "Manga",
    duration: "23 min per ep",
    popularity: 8,
    rank: 421,
    genres: [{ mal_id: 1, name: "Action" }, { mal_id: 2, name: "Adventure" }],
    themes: [{ mal_id: 10, name: "Martial Arts" }],
    demographics: [{ mal_id: 27, name: "Shounen" }],
    studios: [{ mal_id: 1, name: "Studio Pierrot" }],
  },
  {
    animeId: 900004,
    title: "One Piece",
    title_english: "One Piece",
    title_japanese: "One Piece",
    synopsis:
      "Monkey D. Luffy sails the Grand Line with his crew to find the legendary treasure and become the Pirate King.",
    rating: 8.72,
    scored_by: 2200000,
    episodes: 1000,
    status: "Currently Airing",
    type: "TV",
    season: "fall",
    year: 1999,
    seasonYear: "fall 1999",
    image: "https://cdn.myanimelist.net/images/anime/6/73245l.jpg",
    trailer: "https://www.youtube.com/embed/S8_YwFLCh4U",
    trailerImage: "https://img.youtube.com/vi/S8_YwFLCh4U/maxresdefault.jpg",
    source: "Manga",
    duration: "24 min per ep",
    popularity: 4,
    rank: 55,
    genres: [{ mal_id: 2, name: "Adventure" }, { mal_id: 1, name: "Action" }],
    themes: [{ mal_id: 61, name: "Pirates" }],
    demographics: [{ mal_id: 27, name: "Shounen" }],
    studios: [{ mal_id: 18, name: "Toei Animation" }],
  },
  {
    animeId: 900005,
    title: "Demon Slayer: Kimetsu no Yaiba",
    title_english: "Demon Slayer",
    title_japanese: "Kimetsu no Yaiba",
    synopsis:
      "Tanjiro Kamado joins the Demon Slayer Corps after demons slaughter his family and curse his sister.",
    rating: 8.44,
    scored_by: 1900000,
    episodes: 26,
    status: "Finished Airing",
    type: "TV",
    season: "spring",
    year: 2019,
    seasonYear: "spring 2019",
    image: "https://cdn.myanimelist.net/images/anime/1286/99889l.jpg",
    trailer: "https://www.youtube.com/embed/VQGCKyvzIM4",
    trailerImage: "https://img.youtube.com/vi/VQGCKyvzIM4/maxresdefault.jpg",
    source: "Manga",
    duration: "23 min per ep",
    popularity: 6,
    rank: 190,
    genres: [{ mal_id: 1, name: "Action" }, { mal_id: 37, name: "Supernatural" }],
    themes: [{ mal_id: 13, name: "Historical" }],
    demographics: [{ mal_id: 27, name: "Shounen" }],
    studios: [{ mal_id: 43, name: "ufotable" }],
  },
];

module.exports = demoAnimeSeedData;
